#!/bin/bash

function install_sudo() {
  if ! [ -x "$(command -v sudo)" ]; then
    apt-get update && apt-get install sudo
  fi
}

function install_git() {
  if ! [ -x "$(command -v git)" ]; then
    echo "Installing git"
	  sudo apt-get update && sudo apt-get install git
  fi
}

function install_dotfiles() {
  DOTFILES_DIR=~/.dotfiles
  if [ -d "$DOTFILES_DIR" ]; then
    echo "Removing old dotfiles installation"
  	rm -rf ${DOTFILES_DIR}
  fi
  git clone https://github.com/arcanjoaq/dotfiles.git ${DOTFILES_DIR} && cd ${DOTFILES_DIR} && ./install.sh	
}

install_sudo && install_git && install_dotfiles

